### ISSUE TITLE
About output file format

### ISSUE THREAD

**Issue by z-lan** [tianoak/MedicalImageFormatConvert#3]
Hello
The image I got from running your code is in JPEG format. Is it losslessly compressed?
 In addition, can the program get images in TIFF format?
Thank you very much!

**Comment by tianoak** [comment]
Hi,

It is not losslessly compressed. And you can get it in tiff format by using "convert". You can see that on Readme.


________________________________
发件人: wobujiaoluoxaiohei <notifications@github.com>
发送时间: 2018年12月10日 7:13
收件人: tianoak/MedicalImageFormatConvert
抄送: Subscribed
主题: [tianoak/MedicalImageFormatConvert] About output file format (#3)


Hello
The image I got from running your code is in JPEG format. Is it losslessly compressed?
In addition, can the program get images in TIFF format?
Thank you very much!

―

**Comment by z-lan** [comment]
Thank you very much for your reply！
If I make the following changes in the program:
		//BM.Save(gcnew String(str.c_str()), System::Drawing::Imaging::ImageFormat::Jpeg);
		BM.Save(gcnew String(str.c_str()), System::Drawing::Imaging::ImageFormat::Bmp);
and 
		//str.append(".jpeg");
		str.append(".bmp");
The amount of data in the picture will become larger. Is the picture thus obtained in bmp format?

**Comment by tianoak** [comment]
yes, surely it does.
________________________________
发件人: wobujiaoluoxaiohei <notifications@github.com>
发送时间: 2018年12月13日 6:58
收件人: tianoak/MedicalImageFormatConvert
抄送: Huan Tian; Comment
主题: Re: [tianoak/MedicalImageFormatConvert] About output file format (#3)


Thank you very much for your reply！
If I make the following changes in the program:
//BM.Save(gcnew String(str.c_str()), System::Drawing::Imaging::ImageFormat::Jpeg);
BM.Save(gcnew String(str.c_str()), System::Drawing::Imaging::ImageFormat::Bmp);
and
//str.append(".jpeg");
str.append(".bmp");
The amount of data in the picture will become larger. Is the picture thus obtained in bmp format?

―
