### ISSUE TITLE
Fail to convert kfb file

### ISSUE THREAD

**Issue by 7Q2019** [tianoak/MedicalImageFormatConvert#4]
hello, Tian
when I run ConsoleApplication1.exe throw an exception,Can you help to solve the problem,thanks very much.

![微信截图_20190409201652](https://user-images.githubusercontent.com/31687962/55799720-a6538900-5b04-11e9-9b1a-545156a81c9d.png)

**Comment by tianoak** [comment]
you need to contact the company who provides the scanner of kfb files to get the missing dll file.
