### ISSUE TITLE
InitImageFile ERROR with new version of k-viewer and kfb file

### ISSUE THREAD

**Issue by BoPeng** [tianoak/MedicalImageFormatConvert#5]
Hi, @tianoak 

I have k-viewer 1.5.2.5 installed and I am able to view a kfb file with this program (the file was not viewable using an earlier version of the program). I have compiled your project and was able to load the DLL, but I got 

```
InitImageFile ERROR
```
when I try to open this particular kfb file. Since `InitImageFileFun` is the first function called from the DLL, the only thing suspicious is the first parameter, which is of type `ImageInfoStruct`,

```
typedef struct IMAGE_INFO_STRUCT {
	LPARAM DataFilePTR;
} ImageInfoStruct;
```
Do you know if there is any interface change to this data type?

**Comment by tianoak** [comment]
I am sorry that I am not familiar with this change.
